fail_fast: false
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.6
    hooks:
    -   id: clang-format

# -   repo: https://github.com/pocc/pre-commit-hooks
#     rev: v1.3.5
#     hooks:
#     -    id: cppcheck
#          args: [--std=c++17, --language=c++]
